"use client";
import Header from "@/components/Header";
import "./globals.css";
import { Nunito_Sans } from "next/font/google";
import { useEffect, useState } from "react";

const nunito = Nunito_Sans({ subsets: ["latin"] });

export const metadata = {
  title: "Ahmet Furkan Meriç",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  const [darkTheme, setDarkTheme] = useState(true);
  //Theme Alma İşlemi
  useEffect(() => {
    const storedTheme = localStorage.getItem("theme");
    if (storedTheme === "dark") {
      setDarkTheme(true);
    }
  }, []);

  useEffect(() => {
    if (darkTheme) {
      document.body.classList.add("darkTheme");
    } else {
      document.body.classList.remove("darkTheme");
    }
    localStorage.setItem("theme", darkTheme ? "dark" : "light");
  }, [darkTheme]);

  function handleTheme() {
    setDarkTheme(!darkTheme);
  }

  return (
    <html
      className={darkTheme ? "darkTheme" : "lightTheme"}
      // style={{ colorScheme: `${darkTheme ? "dark" : "light"}` }}
    >
      <head>
        <title>Ahmet Furkan Meriç</title>
        <link
          rel="apple-touch-icon"
          sizes="180x180"
          href="/apple-touch-icon.png"
        />
        <link
          rel="icon"
          type="image/png"
          sizes="32x32"
          href="/favicon-32x32.png"
        />
        <link
          rel="icon"
          type="image/png"
          sizes="16x16"
          href="/favicon-16x16.png"
        />
        <link rel="manifest" href="/site.webmanifest" />
      </head>
      <body className={nunito.className}>
        <Header handleTheme={handleTheme} darkTheme={darkTheme} />
        {children}
      </body>
    </html>
  );
}
